### ISSUE TITLE
How is created or uploaded the custom configuration file?

### ISSUE THREAD

**Issue by arlekinjose** [deric/dcos-traefik#3]
Beyond specifying the name of the custom configuration file, e.g rules.tom, how can be place this file inside the container? I do not see any fetch parameter or similar which permits to retrieve the custom configuration file from a file server, web server or filesystem

**Comment by arlekinjose** [comment]
I realize that the traefik service installed from the universe repository uses the Universal Container Runtime (UCR) instead of docker. I see that the container shares the same filesystem that the host. I guess that I can put the custom configuration file in a folder of the host, and set up the parameter like this
"config-file": "rules.toml"
However it did not work yet. I am trying to setup letsencrypt in this rules.toml file. That configuration is not taken into account yet

btw this is my whole configuration

```yaml
{
  "service": {
    "name": "traefik",
    "cpus": 1,
    "mem": 512,
    "instances": 1,
    "user": "root",
    "role": "slave_public",
    "minimumHealthCapacity": 0.5,
    "maximumOverCapacity": 0.2,
    "disk": 100,
  },
  "entrypoint": {
    "http-address": "",
    "http-port": 80,
    "http-compression": true,
    "https-enable": true,
    "https-address": "",
    "https-port": 443,
    "https-compression": true,
    "api-enable": true,
    "enable-dashboard": true,
    "api-port": 8080
  },
  "traefik": {
    "secret-name": "",
    "log-level": "DEBUG",
    "grace-timeout": "30s",
    "healthcheck-interval": "30s",
    "read-timeout": "0s",
    "write-timeout": "0s",
    "idle-timeout": "180s",
    "watch-config-file": true,
    "config-file": "rules.toml"
  },
  "marathon": {
    "enable": true,
    "endpoint": "http://marathon.mesos:8080",
    "watch": true,
    "domain": "marathon.localhost",
    "marathonlb-compatibility": true,
    "expose": true,
    "respect-readiness-checks": true,
    "groups-as-subdomains": false,
    "dialer-timeout": "60s",
    "keep-alive": "10s",
    "force-task-hostname": false
  },
  "mesos": {
    "enable": false,
    "endpoint": "http://leader.mesos:5050",
    "watch": true,
    "domain": "mesos.localhost",
    "expose": true,
    "groups-as-subdomains": false,
    "timeout": 30,
    "zk-timeout": 30,
    "refresh": 30,
    "ip-sources": "host"
  },
  "kubernetess": {
    "enable": false,
    "disable-pass-host-headers": false,
    "enable-pass-tls-cert": false
  },
  "metrics": {
    "recent-errors": 10,
    "prometheus-entrypoint": "",
    "prometheus-buckets": "0.1,0.3,1.2,5.0",
    "datadog-address": "",
    "datadog-pushinterval": "10s",
    "influxdb-address": "",
    "influxdb-pushinterval": "10s",
    "statsd-address": "",
    "statsd-pushinterval": "10s"
  },
  "logging": {
    "access-logs": true
  }
}
```
